# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - nakamura

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # 🟢 DEĞİŞİKLİK: Hedef klasörü 'function' olarak güncelledik
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './function' 
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # 🟢 DEĞİŞİKLİK: Sanal ortamı ve pip yüklemesini function klasörü içinde tetikliyoruz
      - name: Create and start virtual environment & Install dependencies
        working-directory: ./function
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # 🟢 DEĞİŞİKLİK: Sadece function klasörünün içeriğini sıkıştırıyoruz
      - name: Zip artifact for deployment
        run: |
          cd function
          zip -r ../release.zip ./* -x "venv/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AA8D4701CD704721A84B193518D410ED }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_73D96D4A010146DA96CED088AEE3F2B7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A90EB5EA479F437C8C6951BE3B01A2F9 }}

      # 🟢 DEĞİŞİKLİK: Artık paket doğrudan deploy adımının çalıştığı kök dizine açıldığı için 
      # package parametresine '.' vererek hedefi gösteriyoruz.
      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'nakamura'
          slot-name: 'Production'
          package: '.'
